/*
 * Copyright (c) 2026 Oualid Gharach. All rights reserved.
 *
 * Aiming for production-grade standards through clean code and best practices
 * for educational and informational purposes.
 *
 * Created on: 2/3/2026 at 9:11 PM
 *
 * Feel free to use or contribute. Contact: oualid.gharach@gmail.com
 */
package com.mycompany.api.account.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.SQLRestriction;
import org.springframework.data.domain.Persistable;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Customer entity representing the customers table in the database.
 * Uses JPA lifecycle callbacks (@PrePersist, @PreUpdate) for automatic timestamp management.
 *
 * <p>Implements {@link Persistable} to force INSERT on save — without this, Hibernate sees
 * a non-null manually-assigned ID and does a merge (SELECT + UPDATE), which silently
 * overwrites existing rows instead of throwing a constraint violation on collision.</p>
 *
 * <h3>Soft-delete strategy</h3>
 * <ul>
 *   <li>Soft delete is performed in the service layer by setting {@code active = false}
 *       via JPA dirty checking. This keeps the mechanism explicit and visible.</li>
 *   <li>{@code @SQLRestriction("active = true")} automatically filters out inactive
 *       customers from all queries generated by this entity.</li>
 * </ul>
 *
 * <p>Uses @Getter/@Setter instead of @Data to avoid Lombok-generated equals/hashCode
 * on all fields, which is problematic with Hibernate proxies and lazy-loaded collections.
 * equals/hashCode are based on the business key (customerId) only.</p>
 *
 * @author Oualid Gharach
 */
@Entity
@Table(name = "customers")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@SQLRestriction("active = true")
public class Customer implements Persistable<Long> {

    @Id
    @Column(name = "customer_id")
    private Long customerId;

    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 50)
    private String lastName;

    @Column(name = "email", unique = true, nullable = false, length = 100)
    private String email;

    @Column(name = "mobile_number", nullable = false, length = 15)
    private String mobileNumber;

    /**
     * Soft delete flag. Primitive boolean for NOT NULL column — avoids
     * unnecessary boxing and potential NPE from Boolean wrapper.
     */
    @Column(name = "active", nullable = false)
    private boolean active = true;

    /**
     * Accounts owned by this customer.
     * LAZY fetch - explicitly fetched when needed for CustomerDetailedResponse.
     */
    @OneToMany(mappedBy = "customer", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Account> accounts = new ArrayList<>();

    /**
     * Automatically set when entity is first created.
     * Never updated after initial creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Automatically updated on every modification.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * JPA callback - executed before entity is persisted to database.
     * Sets both createdAt and updatedAt on first save.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = Instant.now();
        this.updatedAt = Instant.now();
    }

    /**
     * JPA callback - executed before entity is updated in database.
     * Automatically maintains updatedAt timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    @Override
    public Long getId() {
        return customerId;
    }

    @Override
    public boolean isNew() {
        // createdAt is set by @PrePersist — if null, entity hasn't been persisted yet.
        return createdAt == null;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Customer customer = (Customer) o;
        return customerId != null && customerId.equals(customer.customerId);
    }

    @Override
    public int hashCode() {
        // Constant hashCode for JPA entities with manually assigned IDs.
        // Ensures correct behavior in HashSets/HashMaps before and after persistence.
        return getClass().hashCode();
    }

}